[package]
name = "voicesurf"
version = "0.1.0"
authors = ["Keyhan Vakil <kvakil@voicesurf@kvakil.me>"]
edition = "2018"

[dependencies]
itertools = "0.9.0"
rustc-hash = "1.1.0"
serde = "1.0.114"
serde_json = "1.0"
serde_derive = "1.0.114"
notify = "4.0.15"
xdg = "2.2.0"
byteorder = "1.3.4"
